[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npm run server:build"

[deploy]
startCommand = "npx prisma migrate deploy && node dist-server/server/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
